spring:
  datasource:
    report:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://47.104.74.100:3306/report?serverTimezone=UTC
      druid:
        initial-size: 5
        max-active: 5
        min-idle: 5
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1 FROM DUAL
    report-source:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://47.104.74.100:3306?serverTimezone=UTC
      druid:
        initial-size: 5
        max-active: 5
        min-idle: 5
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1 FROM DUAL



management:
  endpoints:
    web:
      exposure:
        include: health,beans,info

